<?php

return [
    'request_types' => [
        [
            'key' => 'check-repair-computer',
            'name' => 'Check / Repair Computer',
            'follow_up_question' => 'Details/Action Needed',
            'fields' => [['key' => 'details', 'label' => 'Details/Action Needed', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 1,
            'is_active' => true,
        ],
        [
            'key' => 'fix-printer-scanner',
            'name' => 'Fix Printer / Scanner',
            'follow_up_question' => 'System/Application',
            'fields' => [['key' => 'details', 'label' => 'System/Application', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 2,
            'is_active' => true,
        ],
        [
            'key' => 'create-reset-account',
            'name' => 'Create / Reset Account',
            'follow_up_question' => 'Location/Details',
            'fields' => [['key' => 'details', 'label' => 'Location/Details', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 3,
            'is_active' => true,
        ],
        [
            'key' => 'report-network-internet-issue',
            'name' => 'Report Network / Internet Issue',
            'follow_up_question' => 'Account/Action Needed',
            'fields' => [['key' => 'details', 'label' => 'Account/Action Needed', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 4,
            'is_active' => true,
        ],
        [
            'key' => 'extract-database-records',
            'name' => 'Extract Database Records (System / Database)',
            'follow_up_question' => 'Issue/Action Needed',
            'fields' => [['key' => 'details', 'label' => 'Issue/Action Needed', 'type' => 'textarea']],
            'requires_approval' => true,
            'approval_roles' => ['Super Administrator', 'Administrator', 'Division Head', 'Records Chief', 'City Assessor'],
            'sort_order' => 5,
            'is_active' => true,
        ],
        [
            'key' => 'grant-restore-file-access',
            'name' => 'Grant / Restore File Access',
            'follow_up_question' => 'Records/Data',
            'fields' => [['key' => 'details', 'label' => 'Records/Data', 'type' => 'textarea']],
            'requires_approval' => true,
            'approval_roles' => ['Super Administrator', 'Administrator', 'Division Head', 'City Assessor'],
            'sort_order' => 6,
            'is_active' => true,
        ],
        [
            'key' => 'file-folder-access-request',
            'name' => 'File / Folder Access Request',
            'follow_up_question' => 'File/Folder/System',
            'fields' => [['key' => 'details', 'label' => 'File/Folder/System', 'type' => 'textarea']],
            'requires_approval' => true,
            'approval_roles' => ['Super Administrator', 'Administrator', 'Division Head', 'City Assessor'],
            'sort_order' => 7,
            'is_active' => true,
        ],
        [
            'key' => 'setup-fix-email-domain-account',
            'name' => 'Set Up / Fix Email / LGU Domain Account Creation',
            'follow_up_question' => 'Email/Account',
            'fields' => [['key' => 'details', 'label' => 'Email/Account', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 8,
            'is_active' => true,
        ],
        [
            'key' => 'setup-replace-equipment',
            'name' => 'Set Up / Replace IT Equipment',
            'follow_up_question' => 'Equipment/Details',
            'fields' => [['key' => 'details', 'label' => 'Equipment/Details', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 9,
            'is_active' => true,
        ],
        [
            'key' => 'install-configure-software',
            'name' => 'Install / Configure Software',
            'follow_up_question' => 'Software/Application',
            'fields' => [['key' => 'details', 'label' => 'Software/Application', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 10,
            'is_active' => true,
        ],
        [
            'key' => 'troubleshoot-system-application',
            'name' => 'Troubleshoot System / Application',
            'follow_up_question' => 'Issue/Error',
            'fields' => [['key' => 'details', 'label' => 'Issue/Error', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 11,
            'is_active' => true,
        ],
        [
            'key' => 'other-it-request',
            'name' => 'Other IT Request',
            'follow_up_question' => 'Please Specify',
            'fields' => [['key' => 'details', 'label' => 'Please Specify', 'type' => 'textarea']],
            'requires_approval' => false,
            'approval_roles' => [],
            'sort_order' => 12,
            'is_active' => true,
        ],
    ],
];
